user_age = int(input("Please tell me your age: "))
print(f"Your age currently {user_age} years old.")
print(f"In 10 years, you will be {user_age + 10} years old.")
print(f"In 20 years, you will be {user_age + 20} years old.")
print(f"In 30 years, you will be {user_age + 30} years old.")
