first_num = int(input("Enter the first number: "))
second_num = int(input("Enter the second number: "))
print("Thank you!")
print(f"{first_num} + {second_num} = {first_num + second_num}")
print(f"{first_num} - {second_num} = {first_num - second_num}")
print(f"{first_num} / {second_num} = {int(first_num / second_num)}") 
print(f"{first_num} * {second_num} = {first_num * second_num}")
